[tool.briefcase]
project_name = "Sword Drill"
bundle = "com.homegrowntechie"
version = "0.0.1"
url = "https://homegrowntechie.com/sword_drill"
license = "MIT license"
author = 'HomegrownTechie'
author_email = "homegrowntechie@gmail.com"

[tool.briefcase.app.sword_drill]
formal_name = "Sword Drill"
description = "Display spoken Bible references."
icon = "src/sword_drill/resources/sword_drill"
sources = ['src/sword_drill']
requires = []


[tool.briefcase.app.sword_drill.macOS]
requires = [
    'toga-cocoa>=0.3.0.dev20',
]

[tool.briefcase.app.sword_drill.linux]
requires = [
    'toga-gtk>=0.3.0.dev20',
]
system_requires = [
    'libgirepository1.0-dev',
    'libcairo2-dev',
    'libpango1.0-dev',
    'libwebkitgtk-3.0-0',
    'gir1.2-webkit-3.0',
]

[tool.briefcase.app.sword_drill.windows]
requires = [
    'toga-winforms>=0.3.0.dev20',
]

# Mobile deployments
[tool.briefcase.app.sword_drill.iOS]
requires = [
    'toga-iOS>=0.3.0.dev20',
]

[tool.briefcase.app.sword_drill.android]
requires = [
    'toga-android>=0.3.0.dev20',
]
