[tool.briefcase]
project_name = "Sword Drill"
bundle = "com.example"
version = "0.0.1"
url = "https://example.com/sworddrill"
license = "BSD license"
author = 'Jane Developer'
author_email = "jane@example.com"

[tool.briefcase.app.sworddrill]
formal_name = "Sword Drill"
description = "My first application"
icon = "src/sworddrill/resources/sworddrill"
sources = ['src/sworddrill']
requires = []


[tool.briefcase.app.sworddrill.macOS]
requires = [
    'toga-cocoa>=0.3.0.dev20',
]

[tool.briefcase.app.sworddrill.linux]
requires = [
    'toga-gtk>=0.3.0.dev20',
]
system_requires = [
    'libgirepository1.0-dev',
    'libcairo2-dev',
    'libpango1.0-dev',
    'libwebkitgtk-3.0-0',
    'gir1.2-webkit-3.0',
]

[tool.briefcase.app.sworddrill.windows]
requires = [
    'toga-winforms>=0.3.0.dev20',
]

# Mobile deployments
[tool.briefcase.app.sworddrill.iOS]
requires = [
    'toga-iOS>=0.3.0.dev20',
]

[tool.briefcase.app.sworddrill.android]
requires = [
    'toga-android>=0.3.0.dev20',
]
