name: Release:Windows

on:
  push:
    tags:
      - 'v*.*.0'

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Build Windows Executable
      - name: PyInstaller Windows
        uses: JackMcKew/pyinstaller-action-windows@v0.1.2
        with:
          path: src

      # Build Linux Executable
      - name: PyInstaller Linux
        uses: JackMcKew/pyinstaller-action-linux@main
        with:
          path: src

      # Create Artifact
      - name: Save Artifact
        uses: actions/upload-artifact@v2
        with:
          name: SwordDrill
          path: src/dist/windows

      # Publish Release
      - name: Release
        uses: fnkr/github-action-ghr@v1
        env:
          GHR_PATH: src/dist/windows/
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

