name: Release:Windows

on:
#   push:
#     # tags:
#     #   - 'v*.*.0'

  workflow_dispatch:

jobs:
  release:
    name: Create Release
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: macos-latest
            TARGET: macos
            BUILD_COMMAND: /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)" &&
                          brew install portaudio &&
                          brew install pipenv &&
                          pipenv install &&
                          pip install pyinstaller &&
                          pyinstaller -F -w -n SwordDrill -i icon.ico src/main.py &&
                          cd dist/ &&
                          zip -r9 SwordDrill SwordDrill.app/

#           - os: windows-latest
#             TARGET: windows
#             BUILD_COMMAND: python -m venv .venv &&
#                           .venv/Scripts/activate &&
#                           pip install pipenv &&
#                           pipenv install && pipenv shell &&
#                           pyinstaller -F -w -n SwordDrill -i icon.ico main.py

    steps:
      # Checkout Source
      - uses: actions/checkout@v2

      # Install Python
      - uses: actions/setup-python@v2
        with:
          python-version: '3.8' # Version range or exact version of a Python version to use
          architecture: 'x64' # optional x64 or x86. Defaults to x64 if not specified

      # Build Executables
      - name: Build Executables
        run: ${{ matrix.BUILD_COMMAND }}

      # Publish Release
      - name: Create Release
        uses: svenstaro/upload-release-action@2.2.1
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: dist/*
          tag: ${{ github.ref }}
          file_glob: true
