name: Release:Windows

on:
  push:
    # tags:
    #   - 'v*.*.0'

  workflow_dispatch:

jobs:
  release:
    name: Create Release
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: macos-latest
            TARGET: macos
            BUILD_COMMAND: pyinstaller -F -w -n SwordDrill -i icon.ico main.py &&
                        cd dist/ &&
                        zip -r9 SwordDrill SwordDrill.app/

          - os: windows-latest
            TARGET: windows
            BUILD_COMMAND: pyinstaller -F -w -n SwordDrill -i icon.ico main.py

    steps:
      - uses: action/checkout@v2

      # Install pipenv dependencies
      - name: Install Dependecies
        uses: VaultVulp/action-pipenv@v2.0.1
        with:
          command: install -d

      # Build Executables
      - name: Build Executables
        run: ${{ matrix.BUILD_COMMAND }}

      # Save Artifact
      - name: Save Artifact
        uses: actions/upload-artifact@v2
        with:
          name: SwordDrill
          path: dist/

      # Publish Release
      - name: Release
        uses: fnkr/github-action-ghr@v1
        env:
          GHR_PATH: dist/
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

