name: Release

on:
#   push:
#     # tags:
#     #   - 'v*.*.0'

  workflow_dispatch:

jobs:
  release:
    name: Create Release
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: macos-latest
            file_name: SwordDrill-MacOS.tar.gz
            BUILD_COMMAND: /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)" &&
                          brew install portaudio &&
                          brew install pipenv &&
                          python -m venv .venv &&
                          pipenv install &&
                          pip install pyinstaller &&
                          source .venv/bin/activate &&
                          pyinstaller -F -w -n SwordDrill.app -i icon.ico src/main.py &&
                          cd dist/ &&
                          tar -czf MacOS.tar.gz SwordDrill.app/ &&
                          rm SwordDrill.app

          - os: windows-latest
            file_name: SwordDrill-Windows.zip
            BUILD_COMMAND: python -m venv .venv &&
                          .venv/Scripts/activate &&
                          pip install pipwin &&
                          pipwin install pyaudio &&
                          pip install pyinstaller &&
                          pip install pipenv &&
                          pipenv install &&
                          pyinstaller -F -w -n SwordDrill.exe -i icon.ico src/main.py &&
                          cd dist &&
                          Compress-Archive -Path SwordDrill.exe -DestinationPath Windows.zip &&
                          rm SwordDrill.exe

    steps:
      # Checkout Source
      - uses: actions/checkout@v2

      # Install Python
      - uses: actions/setup-python@v2
        with:
          python-version: '3.8' # Version range or exact version of a Python version to use
          architecture: 'x64' # optional x64 or x86. Defaults to x64 if not specified

      # Build Executables
      - name: Build Executables
        run: ${{ matrix.BUILD_COMMAND }}

      # Publish Release
      - name: Create Release
        uses: svenstaro/upload-release-action@2.2.1
        with:
          file: ${{ matrix.file_name }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ github.ref }}
