name: Release:Windows

on:
  push:
    # tags:
    #   - 'v*.*.0'

  workflow_dispatch:

jobs:
  release:
    name: Create Release
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: macos-latest
            TARGET: macos
            BUILD_COMMAND: python -m venv .venv &&
                        source .venv/bin/activate &&
                        pip install pipenv &&
                        pipenv install && pipenv shell &&
                        pyinstaller -F -w -n SwordDrill -i icon.ico main.py &&
                        cd dist/ &&
                        zip -r9 SwordDrill SwordDrill.app/

          - os: windows-latest
            TARGET: windows
            BUILD_COMMAND: pyinstaller -F -w -n SwordDrill -i icon.ico main.py

    steps:
      # Checkout Source
      - uses: actions/checkout@v2

      # Install Python
      - uses: actions/setup-python@v2
        with:
          python-version: '3.x' # Version range or exact version of a Python version to use
          architecture: 'x64' # optional x64 or x86. Defaults to x64 if not specified

      # Build Executables
      - name: Build Executables
        run: ${{ matrix.BUILD_COMMAND }}

      # Save Artifact
      - name: Save Artifact
        uses: actions/upload-artifact@v2
        with:
          name: SwordDrill
          path: dist/

      # Publish Release
      - name: Release
        uses: fnkr/github-action-ghr@v1
        env:
          GHR_PATH: dist/
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

